---
- name: Include OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS specific tasks
  include: "{{ ansible_os_family }}.yml"

- name: Install Neo4j 
  package:
    name: neo4j
    state: present

- name: Ensure graph DB folder exists and has the correct permissions
  file:
    path: "{{ neo4j_server_database_location }}"
    state: directory
    owner: neo4j
    group: "{{ neo4j_group }}"
    mode: 0755

- name: Set the neo4j data directory
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms\.directories\.data=.*'
    line: "dbms.directories.data={{ neo4j_server_database_location }}"
    state: present
  notify: Restart Neo4j

- name: Set the neo4j heap inital size
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms\.memory\.heap\.initial_size=.*'
    line: "dbms.memory.heap.initial_size={{ neo4j_memory_heap_initial_size }}"
    state: present
  notify: Restart Neo4j

- name: Set the neo4j heap max size
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms\.memory\.heap\.max_size=.*'
    line: "dbms.memory.heap.max_size={{ neo4j_memory_heap_max_size }}"
    state: present
  notify: Restart Neo4j

- name: Set the neo4j pagecache size
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^dbms\.memory\.pagecache\.size=.*'
    line: "dbms.memory.pagecache.size={{ neo4j_memory_pagecache_size }}"
    state: present
  notify: Restart Neo4j

- name: Allow any connection to Neo4J
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '^(# )?dbms.connectors.default_listen_address=0.0.0.0'
    line: "dbms.connectors.default_listen_address=0.0.0.0"
    state: present
  when: neo4j_allow_any_connection | bool
  notify: Restart Neo4j

- name: Ensure open files soft and hard limits are set
  copy:
    src: etc/security/limits.d/neo4j.conf
    dest: /etc/security/limits.d/neo4j.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure pam_limits.so is enabled 
  lineinfile:
    dest: /etc/pam.d/su
    regexp: '^(# )?session    required   pam_limits.so'
    line: "session    required   pam_limits.so"
    state: present

- name: Add ulimit to init.d script
  lineinfile:
    dest: /etc/init.d/neo4j
    line: "  ulimit -n 40000"
    insertbefore: "^  start-stop-daemon.*"
  notify: Restart Neo4j

- name: insert/update HTML surrounded by custom markers after <body> line
  blockinfile:
    dest: /etc/init.d/neo4j
    insertbefore: "  ulimit -n 40000"
    content: |
        if [ ! -d /var/run/neo4j ]; then
          mkdir -p /var/run/neo4j
          chown neo4j /var/run/neo4j
          chgrp nogroup /var/run/neo4j
        fi
  notify: Restart Neo4j

- name: Ensure the Neo4j service is enabled and started
  service:
    name: neo4j
    enabled: yes
    state: started
