---
- name: Install which
  package:
    name: which
    state: present

- name: Add Neo4j Yum Repo
  yum_repository:
    name: neo4j
    description: Neo4j Yum Repo
    baseurl: http://yum.neo4j.org/stable
    gpgkey: http://debian.neo4j.org/neotechnology.gpg.key
    gpgcheck: yes